### ISSUE TITLE
Support for public client

### ISSUE THREAD

**Issue by pbuyle** [oauthjs/node-oauth2-server#111]
I'm trying to use node-oauth2-server (via koa-oauth-server) to build an authorization server for a single page web application.

http://tools.ietf.org/html/rfc6749#section-2.1 define such application as a public client. A public client does not have a client_secret (because it could not keep it safe anyway), and is not required to authenticate with the authorization server when requesting a token (see http://tools.ietf.org/html/rfc6749#section-4.3.2).

To support public client, the Grant middleware should accept request without client credential. Then, any function receiving the client id should accept a null client id.

**Comment by bradley-holt** [comment]
+1

**Comment by mjsalinger** [comment]
This issue refers to v2 of the library, closing.
