### ISSUE TITLE
Incorrect userId in mongodb in oauthaccesstokens

### ISSUE THREAD

**Issue by tamtakoe** [oauthjs/node-oauth2-server#121]
When I login, I see in console:

<pre>in getClient (clientId: 1, clientSecret: secret)
in grantTypeAllowed (clientId: 1, grantType: password)
in getUser (username: aaa2, password: 123)
in saveAccessToken (token: b9e409bd008cb2f044b140a7efb89c238cee015e, clientId: 1, userId: { _id: 54463a511abb0644bf99f3a0,
  username: 'aaa2',
  password: '123',
  __v: 0,
  email: '' }, expires: Tue Oct 21 2014 15:56:32 GMT+0400 (RTZ 2 (лето)))</pre>

There is user object instead of user id in oauthaccesstokens document:

<pre>{
    "_id" : ObjectId("54463be0e95f96ecc189f5a8"),
    "accessToken" : "b9e409bd008cb2f044b140a7efb89c238cee015e",
    "clientId" : "1",
    "userId" : "{ _id: 54463a511abb0644bf99f3a0,\n  username: 'aaa2',\n  password: '123',\n  __v: 0,\n  email: '' }",
    "expires" : ISODate("2014-10-21T11:56:32.888Z"),
    "__v" : 0
}</pre>

**Comment by ChrisTerBeke** [comment]
Had the same issue. A lot of examples use this for the saveAccessToken function:

```function(token, clientId, expires, userId, callback)```

While in fact, express returns the whole user object instead of just the id, resulting in this corrected function:

```function(token, clientId, expires, user, callback)```

(the difference is the 4th argument, being user instead of userId.

```
module.exports.saveAccessToken = function(token, clientId, expires, user, callback) {
	var fields = {
		clientId: clientId,
		userId: user.id,
		expires: expires
	};

	OAuthAccessTokensModel.update({ accessToken: token }, fields, { upsert: true }, function(err) {
		if (err) {
			console.error(err);
		}

		callback(err);
	});
};
```
