### ISSUE TITLE
Proposal to move to dedicated oauthjs organisation

### ISSUE THREAD

**Issue by thomseddon** [oauthjs/node-oauth2-server#162]
Following from https://github.com/thomseddon/node-oauth2-server/issues/159#issuecomment-77415120

**Comment by mjsalinger** [comment]
@thomseddon I guess it really depends on where you want this project to go.  I agree with the sentiment that this project is becoming the node.js standard for OAuth2 implementation, and with the features in 3.0 it really will be.  Putting it in its own namespace could open that up a little more, and not change things as far as how the project is run/maintained (unless that is something you wanted to revisit as well).

**Comment by Downchuck** [comment]
@thomseddon if you're going to try supporting hapi and restify, it'd make some sense to move this into its own organization. If it's just express.js, I don't see a reason to create a more complicated structure.

It does look like it's time to take the current release and branch it to 2.x and move master onto 3.x.

**Comment by thomseddon** [comment]
Yes I'd like to do some work on 3.0.0 now - have quite a few things lined up for it!

**Comment by mjsalinger** [comment]
It seems this project has picked up a lot of interest in the last few months - the # of issues and PRs seems to be increasing, and it may benefit from something like this, with a group of core collaborators and known procedures for contributing/testing/releasing, to allow for more regular releases.  WDYT @thomseddon ?

**Comment by sunnycmf** [comment]
+1 support for including core contributors so that PR can be review/accessed faster and features can be evaluated in faster pace.

**Comment by thomseddon** [comment]
I'm wary of adding too much process etc. but I will have a go at documenting how you become a collaborator and what to do if you are

**Comment by mjsalinger** [comment]
@thomseddon In #255 @ruimarinho made another good case for moving this to an org - so that multiple projects could all be grouped together, like wrappers/examples for different storage engines, middleware, etc.

**Comment by thomseddon** [comment]
Heyo,

If this is in everyone's preference then I'm happy to go along :)

We could incorporate:

- this project
- https://github.com/seegno/express-oauth-server
- https://github.com/thomseddon/koa-oauth-server

?

**Comment by thomseddon** [comment]
Also: https://github.com/seegno/angular-oauth2

**Comment by thomseddon** [comment]
I've created this: https://github.com/oauthjs and invited @mjsalinger @nunofgs @ruimarinho 

Name is deliberately generic but open to suggestions as always

**Comment by mjsalinger** [comment]
I like the name - it's easy to remember and presents itself as the authoritative OAuth solution for Javascript.

**Comment by mjsalinger** [comment]
Now that the org is there, should we move the promises referenced by @thomseddon to the new org?  

I'm also thinking of writing an OpenID connect extension that could go in there as well (unless we think that would be better in the core library). 

/cc @nunofgs @ruimarinho

**Comment by thomseddon** [comment]
If no objections in the next few days I'll push the button and move this and the koa module to the new org - not sure if github handles redirects but if not I'll put a note up

**Comment by mjsalinger** [comment]
Sounds good!  `express-oauth-server` was moved yesterday.

**Comment by ruimarinho** [comment]
No objections here. `angular-oauth` should make the shift until the end of the week too.

**Comment by thomseddon** [comment]
Done! Github is 301'ing from the old location to here :tada:
