### ISSUE TITLE
the parameter user in method getAccessToken seems like a string

### ISSUE THREAD

**Issue by gfafei** [oauthjs/node-oauth2-server#233]
readme.md writes that the parameter is a object, when i use it , it is a Id stirng;

**Comment by deefactorial** [comment]
check out these tests

https://github.com/thomseddon/node-oauth2-server/blob/master/test/authorise.js#L188-L238

it depends on what you set as the user in model.saveAccessToken if you set a string you get back a string if you set an object you get an object.
