### ISSUE TITLE
Protect against undefined properties object in OAuthError

### ISSUE THREAD

**Issue by mjsalinger** [oauthjs/node-oauth2-server#248]
In `OAuthError`, the properties object could throw if undefined.  While not part of the public API, it's good to defend against unforeseen situations of future modifiers of the code - for example, if someone else writes another method that calls OAuthError but misses the test for it.

**Comment by thomseddon** [comment]
This was fixed in the 3.0.0 release and is checked in the current code: https://github.com/oauthjs/node-oauth2-server/blob/e1f741fdad191ee47e7764b80a8403c1ea2804d4/lib/errors/oauth-error.js#L16-L19
