### ISSUE TITLE
Examples unavailable in 3.0.0 commit

### ISSUE THREAD

**Issue by divyekhanna** [oauthjs/node-oauth2-server#253]
Hi, great to see PR #203 merged!

I would just like to point out that examples (as pointed to by the Readme), are not available here: https://github.com/thomseddon/node-oauth2-server/blob/master/examples/password

Please add the examples. I'm looking for password grant type.

Thanks.

**Comment by manjeshpv** [comment]
Refer full impl https://github.com/manjeshpv/node-oauth2-server-implementation
