### ISSUE TITLE
where is example source code?

### ISSUE THREAD

**Issue by kimyongin** [oauthjs/node-oauth2-server#261]
A simple password grant authorization example.
A more complex password and refresh_token example.
An advanced password, refresh_token and authorization_code (with scopes) example.

this link is broken..
https://github.com/thomseddon/node-oauth2-server/blob/master/examples/password

**Comment by mjsalinger** [comment]
Still in progress for v3...

**Comment by ngrices** [comment]
Any update on the examples being ready?

**Comment by manjeshpv** [comment]
using "oauth2-server": "^3.0.0-b2",
Using: ExpressJS, Sequelize, Mongoose - Supports MongoDB, PostgreSQL, MySQL, MariaDB, SQLite and MSSQL

https://github.com/manjeshpv/node-oauth2-server-implementation

**Comment by thomseddon** [comment]
More examples can also be found here: https://github.com/14gasher/oauth-example

I hope to merge more examples back into the main docs in the future!
