### ISSUE TITLE
Timeline on 3.x release

### ISSUE THREAD

**Issue by jasonblanchard** [oauthjs/node-oauth2-server#278]
Hi there,

I'm testing the `master` branch in a reference application and running into a few issues following the upgrade 2.x to 3.x migration guide. I also don't see a 3.x NPM release or a stable 3.x tagged branch.

What's the approximate timeline on a stable 3.x release? We're hoping to release a pretty substantial application in a few weeks, just wondering if I should stay on v2 for now or track the 3.x changes.

Thanks!

**Comment by mjsalinger** [comment]
Hi there,

We're hoping to release the 3.x branch in the next couple of weeks - if you are running into issues, please share them so we can address any bugs before the final release.

**Comment by jasonblanchard** [comment]
OK great. I'll take a closer look at the issues I was having - didn't want to bother if there was still a lot of churn.

Thanks.
