### ISSUE TITLE
Better Model Spefication.

### ISSUE THREAD

**Issue by brunolazzaro** [oauthjs/node-oauth2-server#296]
I feel like the model specification is missing some information that makes the implementation of each method possible.

Right now it seems that each method signature (the parameters it recieves) and the expected output is missing. The examples provided seem a little too vague.

For instance the **saveToken** method states "Must return an object with the request user, client and scope" but no info is provided regarding what parameters it takes in and the example output is `{ accessToken: '123dsd21eydgeweg2e' }` which does not seem to match what is stated on the description.

Is there any info I'm missing? Thanks. 

P.S: Also this might be related to #287, since it would be much more easy to implement based off the examples.

**Comment by Mirodil** [comment]
+1

**Comment by janjilek** [comment]
+1 - it's really annoying. I am trying to implement it and have no idea, what is wrong

**Comment by manjeshpv** [comment]
SQL:
model: https://github.com/manjeshpv/node-oauth2-server-implementation/blob/master/components/oauth/models.js
ORM: https://github.com/manjeshpv/node-oauth2-server-implementation/tree/master/components/oauth/sqldb
Mongo:
Dump: https://github.com/manjeshpv/node-oauth2-server-implementation/tree/master/components/oauth/mongodb
MongooseODM: https://github.com/manjeshpv/node-oauth2-server-implementation/blob/master/components/oauth/mongo-models.js

**Comment by payne8** [comment]
+1 thanks @manjeshpv for those links they are very helpful. I still feel it would be good to update the model specification to explicitly show what is needed for each function and when (and how) to fail the challenges.

**Comment by maxtruxa** [comment]
I wrote a full model specification for myself, detailing how the signature of each function is supposed to look and which function is required by which grant flow. Also, there's a minimal, annotated example for every function.
This currently includes functionality added by pending PRs, so I'll have to see what made it into the master so far and what hasn't. Note to myself: Might be a good idea to submit several PRs; one for the current master and one for every PR that adds to/changes the model.
I'll put that in an appropriate format and submit PR(s) sometime this week.

**Comment by p-bakker** [comment]
Hi maxtruxa, 

Any progress on those PR's with better docs? could really use some

Paul

**Comment by maxtruxa** [comment]
Documentation now includes a [model overview](http://oauth2-server.readthedocs.io/en/latest/model/overview.html) giving a brief overview over the various supported grants and indicating which model functions are used by which grant.
The [model specification](http://oauth2-server.readthedocs.io/en/latest/model/spec.html) describes what is expected from each model function in detail.

Please direct any suggestions for improvements to the PR (#369). 😄
