### ISSUE TITLE
Change output format to array of an object instead of an object

### ISSUE THREAD

**Issue by mistercorea** [oauthjs/node-oauth2-server#297]
Currently, I am getting an output as 
{
  "token_type": "bearer",
  "access_token": "e9054d8c5bc095e97c758f23f2766283484a01e3",
  "expires_in": 3600
}

but I would like to change to 
[
    {
      "token_type": "bearer",
      "access_token": "e9054d8c5bc095e97c758f23f2766283484a01e3",
      "expires_in": 3600
    }
]

Is this possible?

**Comment by mjsalinger** [comment]
No, the OAuth spec specifies that the format be in the form of an object.  Specifically:  

```
The parameters are included in the entity-body of the HTTP response using the "application/json" media type as defined by [RFC4627].  The parameters are serialized into a JavaScript Object Notation (JSON) structure by adding each parameter at the highest structure level.
```

See https://tools.ietf.org/html/rfc6749#section-5.1
