### ISSUE TITLE
Bad `token` passed to `saveToken` for authorization_code grant

### ISSUE THREAD

**Issue by maxtruxa** [oauthjs/node-oauth2-server#304]
I might be completely wrong here, but the `token` object passed to `saveToken` by the `AuthorizationCodeGrantType` looks.. wrong.

Copied from [here](https://github.com/oauthjs/node-oauth2-server/blob/cd7776ce19b4e55a0e5800d78e4186c741711b36/lib/grant-types/authorization-code-grant-type.js#L185):

```
var token = {
    accessToken: accessToken,
    authorizationCode: authorizationCode,
    refreshToken: refreshToken,
    scope: scope
};
```

Why would anyone want to save an authorization token that has just been used (and revoked because of this [_right before_](https://github.com/oauthjs/node-oauth2-server/blob/cd7776ce19b4e55a0e5800d78e4186c741711b36/lib/grant-types/authorization-code-grant-type.js#L162))?

Also expiration dates for access token and refresh token are missing.

IMO the arguments to `saveToken` should look pretty much the same as for the [password grant](https://github.com/oauthjs/node-oauth2-server/blob/cd7776ce19b4e55a0e5800d78e4186c741711b36/lib/grant-types/password-grant-type.js#L104):

```
var token = {
    accessToken: accessToken,
    accessTokenExpiresAt: accessTokenExpiresAt,
    refreshToken: refreshToken,
    refreshTokenExpiresAt: refreshTokenExpiresAt,
    scope: scope
};
```

If nobody tells me I'm looking at this completely wrong, I'll submit a PR. (I looked through all open PRs, there is none addressing this.)

**Comment by LucianoGanga** [comment]
Regarding the part where you say that the saveToken should look the same as for the password grant, I'm having the same problem, because I need the expiration time for the refresh token and the access token (if the access token doesn't expire, what's the point of having a refresh token?)
