### ISSUE TITLE
Confusing docs / Mixed versions ? 

### ISSUE THREAD

**Issue by LucianoGanga** [oauthjs/node-oauth2-server#305]
Hello! 

I'm trying to use your module since last week, and I'm having a few problems understanding what's going on here: 

- The docs here refer to the v3, that can't be downloaded directly from NPM (I could download it using npm install oauth2-server@next ). That was very confusing and made me loose a day trying to understand why the docs didn't match the code :( 

- There are 2 npm modules: 
`https://www.npmjs.com/package/oauth2-server` => contains v2.4.1
`https://www.npmjs.com/package/node-oauth2-server` => contains v2.4.0

- The docs for v3 says that the module is agnostic, and that it can be used with this modules: 
For KOA: `https://github.com/oauthjs/koa-oauth-server`
For Express: `https://github.com/seegno/express-oauth-server`

- After getting the npm module for the KOA wrapper, I noticed that it was made for the v2.4.1 of oauth2-server. So, I checked GitHub repository (https://github.com/oauthjs/koa-oauth-server), and the package.json of the module points to another version of the oauth2-server module: `seegno-forks/node-oauth2-server#enhancement/refactor-project`. With that, I found this repo: `https://github.com/seegno-forks/node-oauth2-server` (which btw, has the docs for the v2.4.1)

- I need to use the authorization code grant type, but I can't find how to use it with the KOA wrapper with the last versions.

So, after all that, my questions are: 
1) Which version is correct? I need this for a production environment.
2) Is there an example using the authorization-code grant type?

Thanks! 
Luciano

**Comment by maxtruxa** [comment]
There are already multiple issues regarding these problems (#296, #287, #286, #277, #261).

The project is currently in transition to v3. The master reflects the latest state of the pre-release v3 (right now: 3.0.0-b2).

The stable version on npm is `oauth2-server` (2.4.1). This version does *not* use an express/koa/whatever wrapper. For documentation look at the [readme on npm](https://www.npmjs.com/package/oauth2-server). The commit hash for 2.4.1 is [b36a06b445ad0a676e6175d68a8bd0b2f3353dbf](https://github.com/oauthjs/node-oauth2-server/commit/b36a06b445ad0a676e6175d68a8bd0b2f3353dbf).

**Comment by LucianoGanga** [comment]
Thanks @maxtruxa ! 

I finally managed to make all the things work. 

The only problem left is the missing `accessTokenExpiresAt` and `refreshTokenExpiresAt` parameter in the authorization-code grant type. I'll open an issue with that. 

Thanks!
Luciano
