### ISSUE TITLE
No implicit grant? Also, what's up with the refresh tokens?

### ISSUE THREAD

**Issue by juandiegopalomino** [oauthjs/node-oauth2-server#317]
I'm a little bit confused: the repo _claims_ to be rfc compliant, but instead of offering the implicit grant type, it has a "refresh token" grant. While it makes sense that there is a form of refreshing an access token, I don't understand the purpose of the grant: if someone has the refresh token (a requirement for a valid request), then clearly said person got permission to have a refresh token.
Which leads to the point of the hack-ish refresh tokens. To my knowledge, refresh tokens are not really supposed to expire, yet they have a default expiration date shorter than some access token lifetimes I've seen on the web (imgur ftw). Let's assume then that we support perishable refresh tokens: why are they then destroyed after one use? A refresh token is to be used multiple times, and yet here it is revoked after a single use. Let us again be generous and say that we shall support this possibility. Yet, to my knowledge there is no way of allowing the standard behavior and preserving the refresh token.

Is there something big that I'm missing?

**Comment by juandiegopalomino** [comment]
Upon reading [the specs](https://tools.ietf.org/html/rfc6749), it has become clear that there are more grant types, than the authorization grant, including a refresh_token one. I was wrong about that, sorry. The refresh token quirks (e.g. their destruction after one use) still makes little sense to me.

**Comment by maxtruxa** [comment]
There's a difference between *compliant* and *implement every single feature*. AFAIK the spec nowhere states that an implementation has to support every grant flow.

PR #271 adds support for the implicit grant flow.

PR #280 adds the server options `alwaysIssueNewRefreshToken` which allows you to keep the refresh token alive by setting it to `false`.

**Comment by juandiegopalomino** [comment]
@maxtruxa thank you for the clarification! I'll use those pull requests.

**Comment by mjsalinger** [comment]
@juandiegopalomino - The OAuth spec actually proposes such an approach of rotating the refresh token upon use for security reasons.  Many implementations of OAuth I've seen employ this - an access token can be used many times until it expires, and a refresh token can be used once to obtain a new access token, which includes a refresh token.   

> For example, the authorization server could employ refresh token rotation in which a new refresh token is issued with every access token refresh response.  The previous refresh token is invalidated
but retained by the authorization server.

Expiring a refresh token is also a good practice - to ensure nothing lives forever. It's not proposed by the spec, nor is it prohibited (indeed nothing in the spec says that refresh tokens have an infinite lifetime).

As @maxtruxa said, this library is OAuth compliant, but doesn't necessarily implement every feature in the spec.    

However, as @maxtruxa said, we will be adding an option where you can disable the issuing a new refresh token as well as the implicit grant flow.
