### ISSUE TITLE
Promise returns not working

### ISSUE THREAD

**Issue by andyrichardson** [oauthjs/node-oauth2-server#322]
My following promise-based implementation is not working - that is to say, the following function _grantTypeAllowed_ is not being called

    getClient: function(clientId, clientSecret) {
        return new Promise(function(resolve, reject){
            return resolve('10');
        });
    }

When using a callback based approach, this issue no longer stands
     
    getClient: function(clientId, clientSecret, callback){
        return callback(null, '10');
    }

I'm used to using bluebird promises so it is very possible that I'm doing something wrong with the JavaScript promise library. Thanks in advance.

**Comment by maxtruxa** [comment]
Which module version are you using exactly?

The usage of `Promise` looks correct. Note that both `return`s are superfluous, but shouldn't hurt.

**Comment by maxtruxa** [comment]
Also, you said `grantTypeAllowed` is not being called but show `getClient`? Which one isn't being called?

**Comment by andyrichardson** [comment]
> Also, you said grantTypeAllowed is not being called but show getClient. Which one isn't being called?

Apologies @maxtruxa I mustn't have been clear. _grantTypeAllowed_ is the function which should be called by oauth2-server following the completion of the _getClient_ function.

When using the callback approach, _grantTypeAllowed_ is called. When using the promise approach, _grantTypeAllowed_ is not called. I believe this should not be the case as both code snippets should produce identical results.

**Comment by maxtruxa** [comment]
@andyrichardson Oh, I see.

Judging from the fact that you have `grantTypeAllowed` on your model I assume that you're using the version published on npm (v2). That version does not support promises at all.

Promise support will be coming with v3, but that one isn't released yet (see #313).

If you want to use promises inside your model you can of course do that and forward the result on resolution/rejection to the callback.

**Comment by andyrichardson** [comment]
@maxtruxa Thanks, I incorrectly assumed the master branch would be in sync with the release on npm.
