### ISSUE TITLE
store user information in access token

### ISSUE THREAD

**Issue by mattipr** [oauthjs/node-oauth2-server#326]
there is no option to store user information in access token, like userid , why does I need to go always databse to check that user is valid or not, for security we already have refresh token.

**Comment by maxtruxa** [comment]
You can generate the access tokens however you like. PR #303 adds client, user and scope parameters to all the "generate" functions on the model which enables you to use e.g. JWTs.
Note that if you want to keep the ability to revoke access tokens (which usually is a good idea) you would still need to hit the database to check if the token was revoked.

**Comment by mattipr** [comment]
Thanks , I was looking for that. Using JWT for token generation with User Info.
