### ISSUE TITLE
Tagging Release

### ISSUE THREAD

**Issue by chainlink** [oauthjs/node-oauth2-server#328]
Hey guys, I noticed the last tag/release is way back at 2.2.1. Can we get an updated 3.x tag pushed?

**Comment by mjsalinger** [comment]
Will be tagging a 3.0.0-b1 release this week, hopefully.

**Comment by pschwyter** [comment]
Any update on when the next release will be pushed?

**Comment by mjsalinger** [comment]
This week.

**Comment by chainlink** [comment]
Sorry to keep buggin ya? Any update?

**Comment by mjsalinger** [comment]
3.0.0-b3 has been pushed to npm as `next`.

**Comment by chainlink** [comment]
Nice! Thanks 👍
