### ISSUE TITLE
Include WWW-Authenticate headers

### ISSUE THREAD

**Issue by tomekc** [oauthjs/node-oauth2-server#33]
When invalid token is provided by client, provider returns 401 response.

According to HTTP specs, it must be accompanied with WWW-Authenticate header: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2

And actually there are some picky HTTP clients, for example on Samsung Android phones, which are throwing exception when there is no header.

**Comment by hleeanexinet** [comment]
The original issue was about not having WWW-Authenticate header on 401 responses, but cfdadcf adds that header only to 400 responses, not to 401. Am I missing something?
