### ISSUE TITLE
regression, changes applied by PR #303 are missing from master (Generate token params)

### ISSUE THREAD

**Issue by alfonsodev** [oauthjs/node-oauth2-server#334]
PR #303 "Generate token params"
Is missing from the history and definitively not in master.
Was it intended ? 

Thanks.

**Comment by maxtruxa** [comment]
I just looked through all recent commits and the changes are really nowhere to be found. This was definitely **not** intended.

@mjsalinger Any idea how this happened?

**Comment by mjsalinger** [comment]
@maxtruxa Not sure how it happened at all!  I just remerged the branch to master and pushed it.

**Comment by alfonsodev** [comment]
maybe an accident with git rebase ? some accidentally history rewriting can happen when using `git rebase`
