### ISSUE TITLE
Change status code to 4xx

### ISSUE THREAD

**Issue by chainlink** [oauthjs/node-oauth2-server#339]
500 status code indicates server error when an invalid argument is a client error

https://github.com/oauthjs/node-oauth2-server/blob/master/lib/errors/invalid-argument-error.js#L17

Should be changed to `400 Bad Request`

I can make a PR if you agree

**Comment by maxtruxa** [comment]
The purpose of `InvalidArgumentError` is to indicate programming errors on the server side. So in general, the use of `500 Internal Server Error` is correct.
Did you see a `500` response that was triggered by sending invalid data from the client?

**Comment by chainlink** [comment]
ah, i saw it here https://github.com/oauthjs/express-oauth-server/blob/master/index.js#L6

but you're totally right, it's used to throw an error if the model is not specified. Thanks!
