### ISSUE TITLE
Update docs for v3

### ISSUE THREAD

**Issue by mjsalinger** [oauthjs/node-oauth2-server#341]

**Comment by maxtruxa** [comment]
I'll try to get this done during the weekend.

**Comment by maxtruxa** [comment]
@mjsalinger What do you think about using Sphinx/reStructuredText instead of Markdown and moving docs to [readthedocs.org](https://readthedocs.org)?
I'm kind of unhappy with the styling capabilities of Markdown regarding documentation. Plus, RTD would enable us to keep docs for each published version and automatically publish/update docs for new ones.

**Comment by mjsalinger** [comment]
That's not a bad idea.  Given the complexity of the library, I think having more robust docs beyond a basic README is a good idea.

**Comment by maxtruxa** [comment]
Porting What I already wrote from Markdown to reST was a bit more work than expected. I'm currently restructuring documentation and will try to get this out of the door early next week.

**Comment by jsilveira** [comment]
So, everything here: https://github.com/oauthjs/node-oauth2-server/wiki/Model-specification is outdated and is wrong for v3?

**Comment by maxtruxa** [comment]
@jsilveira I think that Wiki article is partially (maybe mostly) up-to-date, but quite a few changes were made since it was written.

**Comment by mjsalinger** [comment]
How's this going @maxtruxa?

**Comment by luiseduardobrito** [comment]
Any update?

**Comment by adamlc** [comment]
Any updates on this?

**Comment by abarisic86** [comment]
@maxtruxa can I help with this?

**Comment by slavab89** [comment]
Any progress? It seems the project kinda stopped developing?

**Comment by maxtruxa** [comment]
Hey guys, sorry this took so long. Docs are finally [up and running](https://oauth2-server.readthedocs.io).

I would appreciate any feedback you can provide on the PR (#369).

**Comment by maxtruxa** [comment]
Closing in favor of #369.
