### ISSUE TITLE
Commit appears to have been lost?

### ISSUE THREAD

**Issue by chainlink** [oauthjs/node-oauth2-server#343]
https://github.com/oauthjs/node-oauth2-server/pull/318

I can't find this PR anywhere in the master branch..

**Comment by johnf** [comment]
I've had a quick look for this as well. It's the main thing preventing me from switching back to upstream.

It looks like it was merged at some stage so maybe lost in a later push -f ?

**Comment by johnf** [comment]
I've created #344 to fix

**Comment by chainlink** [comment]
Nice! Well done

**Comment by mjsalinger** [comment]
Yeah, I think I did a bad rebase at some point that messed a couple of things up.   Thanks for the PR!

**Comment by mjsalinger** [comment]
Done, up on npm.

**Comment by chainlink** [comment]
Thanks all!
