### ISSUE TITLE
Retrieve user from request

### ISSUE THREAD

**Issue by rjoniuqa** [oauthjs/node-oauth2-server#349]
Previously the user is set in the req object. 
But I can't find the user object in the request anymore. Instead it is in the `res.locals.oauth.token.user` object.
Is this correct or am I doing something wrong?

**Comment by maxtruxa** [comment]
Yes, this is correct. See [my comment](https://github.com/oauthjs/node-oauth2-server/issues/327#issuecomment-254269482) in #327.

With `express`, you can use a middleware like this after `authenticate` to get the old behavior back:

```
function(req, res, next) {
  let oauth = res.locals.oauth;
  if (oauth && oauth.token && oauth.token.user) {
    req.user = oauth.token.user;
  }
  next();
}
```

**Comment by rjoniuqa** [comment]
Got it, thank you!
