### ISSUE TITLE
invalid_argument: 500 Invalid argument: `request` must be an instance of Request

### ISSUE THREAD

**Issue by crapthings** [oauthjs/node-oauth2-server#361]
what is this all about ?

trying to upgrade 2x to 3x

**Comment by maxtruxa** [comment]
Use [express-oauth-server](https://github.com/oauthjs/express-oauth-server) instead of this package. The express wrapper handles construction of `Request` instances from express' request object (amongst other thing).

**Comment by crapthings** [comment]
it works!
