### ISSUE TITLE
Exception while invoking method 'oauth2/authCodeGrant' Error: Missing parameter: `headers`

### ISSUE THREAD

**Issue by crapthings** [oauthjs/node-oauth2-server#362]
i followed Migrating from 2.x to 3.x, replace new api but failed

'oauth2/authCodeGrant' is a meteor method call.

it seems oauth2-server 3.x change "authCodeGrant" to "authorize".

https://github.com/prime-8-consulting/meteor-oauth2/blob/master/packages/meteor-oauth2-server/server.js#L104.

i've forked this repo, want to upgrade it to 3.x.

**Comment by crapthings** [comment]
https://github.com/prime-8-consulting/meteor-oauth2/blob/master/packages/meteor-oauth2-server/server.js#L164

these fields are missing in req.

req.headers, req.method

**Comment by crapthings** [comment]
after add these line, still no working.

req.headers['content-type'] = 'application/x-www-form-urlencoded';
req.method = 'POST';

**Comment by crapthings** [comment]
```
curl https://install.meteor.com/ | sh
git clone https://github.com/crapthings/meteor-oauth2
cd meteor-oauth2
git checkout oauth2-server-3
cd examples/resourceServer
meteor npm i
meteor -p 3100
```

register an account and click "Authorize Button" at section Step A5.1 - Generate Access Tokens

**Comment by mjsalinger** [comment]
Hi @crapthings, what exactly are you trying to do?  Would be glad to help.

**Comment by crapthings** [comment]
2.4.1 works fine. never mind.
