### ISSUE TITLE
No Examples?

### ISSUE THREAD

**Issue by pmiotto** [oauthjs/node-oauth2-server#367]

**Comment by Luomusha** [comment]
+1,Example found 404.

**Comment by macogala** [comment]
@Luomusha where did you find examples? Thanks

**Comment by zinevych** [comment]
+1 to this issue. All i've to fully dive into sources of this package to understand how it should be used properly.

**Comment by macogala** [comment]
+1, I can't basically understand anything. @zinevych maybe you have some good hints?
Thanks

**Comment by uschmann** [comment]
+1 Same for me.

This looks really promising and it seems like you put lots of effort into it.

I will give your library a try now and would be willing to do a PR when i have something simple up and running.

Thanks

**Comment by uschmann** [comment]
We just did a quick and dirty implementation of the model without a backing-database.
Take a look here to get inspired.

Some hints:
Start the server and run this to get a bearer token:
```bash
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: c3df2fab-440f-09e4-0c5c-c9f46ef9836b" -d 'username=foo&password=bar&grant_type=password&client_id=publicClientId&client_secret=secretClientSecret' "http://localhost:3000/oauth/token"
```

After this do this to access the secret area:
```bash
curl -X GET -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Bearer YOUR_TOKEN" -H "Cache-Control: no-cache" -H "Postman-Token: 0f69e823-de90-b56e-265f-1c8ed5a57de2" "http://localhost:3000/"
```

**Comment by njj** [comment]
@uschmann These are based off the older version(s).

**Comment by slavab89** [comment]
I've created an example that uses mongo and the latest version
https://github.com/slavab89/oauth2-server-example-mongodb

**Comment by jy95** [comment]
Thanks. If you have time, why no make an example with postgresql ? Don't know if this example is still valid : https://github.com/marsanla/node-oauth2-server-restify/tree/master/examples/postgresql

**Comment by dkushner** [comment]
Any chance we could get some examples that properly implement scopes? I cannot for the life of me figure out the proper way to pass scopes to the saveToken method without reimplementing the entire token generation logic.

**Comment by bjpbakker** [comment]
Few days ago I published a blog post with some of the documentation I wish I had when implementing authorization_code grant. Hope it helps someone.

https://zilverline.github.io/2017/03/17/nodejs-oauth2-provider

Also, if you spot any mistakes or I have missed something, please let me know :)

**Comment by njj** [comment]
@bjpbakker Re your blog post:  I did the same exact thing, just ended up diving into the source code and reading how things worked.  While it was not the most pleasant experience, as I'd rather have some clear documentation to read, I found that my understanding of the library (and oauth in general) is better because of it.

**Comment by mjsalinger** [comment]
We're close to having some full documents.  If anyone has any examples they've written, could you submit them as PRs?  We'd love to use them!

**Comment by manjeshpv** [comment]
@mjsalinger look at #393 as of my experience oauthjs.slack.com is better way to help developers to reply realtime. and we need to build examples of different use cases. like below

https://bshaffer.github.io/oauth2-server-php-docs/ 
see cookbooks section in left sidebar: https://docs.minio.io/
