### ISSUE TITLE
example url does not exist

### ISSUE THREAD

**Issue by calidion** [oauthjs/node-oauth2-server#387]
url in readme:
https://github.com/oauthjs/node-oauth2-server/blob/master/examples/password

does not exist

**Comment by Luomusha** [comment]
+1

**Comment by aftab0000** [comment]
Can you please fix the example url?

**Comment by maxtruxa** [comment]
Please [look at existing issues](https://github.com/oauthjs/node-oauth2-server/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20examples) before opening a new one.

The current master is *not* what's published on npm (`2.x`), but the upcoming version 3 of the project. You can start using v3 right away though using `npm install oauth2-server@next`.

If you need examples for version 2 you can look at this commit: [b36a06b445ad0a676e6175d68a8bd0b2f3353dbf](https://github.com/oauthjs/node-oauth2-server/commit/b36a06b445ad0a676e6175d68a8bd0b2f3353dbf).

Development of examples for version 3 is tracked in issue #342. Documentation as well as an updated README (without the broken link to the examples) is included in PR #369.

Closed as duplicate.
