### ISSUE TITLE
Custom token

### ISSUE THREAD

**Issue by theohdv** [oauthjs/node-oauth2-server#392]
Hey, 
I was looking for creating custom token (jwt) but i found nothing about that. Anyone can give me an hint or a link where it is explained ?

Thanks !

**Comment by manjeshpv** [comment]
See this
https://github.com/manjeshpv/node-oauth2-server-implementation/pull/9/commits/38d142d540153f90e8f2bb349f26f478b2a033a3

**Comment by theohdv** [comment]
yeah thanks but just found this doc: https://github.com/oauthjs/node-oauth2-server/wiki/Migrating-from-2.x-to-3.x .
My bad.

**Comment by manjeshpv** [comment]
you migrating from 2.x to 3.x ?

**Comment by theohdv** [comment]
No but documentation is not updated so i tried to use generateToken method (old documentation). And I found the migration doc which give the new model specifications.

**Comment by manjeshpv** [comment]
Can you join https://oauthjs.slack.com I need to discuss

**Comment by maxtruxa** [comment]
With v3, the model's [`generateAccessToken`](http://oauth2-server.readthedocs.io/en/latest/model/spec.html#model-generateaccesstoken) and [`generateRefreshToken`](http://oauth2-server.readthedocs.io/en/latest/model/spec.html#model-generaterefreshtoken) receive client, user and scope as arguments, making it possible to return JWTs as access tokens.

**Comment by nanachimi** [comment]
Any idea how to add custom fields to a response body of a token endpoint? 
Details: https://github.com/oauthjs/express-oauth-server/issues/67
Source code: https://github.com/nanachimi/oauthserverjs
