### ISSUE TITLE
Restoring master branch to npm version 

### ISSUE THREAD

**Issue by manjeshpv** [oauthjs/node-oauth2-server#395]
@maxtruxa 
Restoring master branch to npm version will resolve many of the issues temporarily.

and actively we can continue with 2.x fixes and feature requests

**Comment by mjsalinger** [comment]
I'm not sure what you're asking for here..  We're planning on releasing 3.x within a week, and 2.x will is no longer being supported.

**Comment by maxtruxa** [comment]
I think what he's saying is that master should always be in sync with npm.

This can be achieved by following a branching model like [this one](http://nvie.com/posts/a-successful-git-branching-model/) (which is what I usually do). Merged but not yet published changes should reside in their own "dev", "devel", or whatever branch.

I'm all for doing this once 3.x is published, but restoring 2.x would be counter-productive at this stage.

**Comment by dtiziani** [comment]
Is there any date you guys are releasing v3 with examples in npm? I'm trying to use, both v2 and v3, but without success. I need a simple flow with credentials/refresh/access tokens, I've already tried all the examples from github, but it always fails.

**Comment by codeitcody** [comment]
`npm install oauth2-server` is still installing at "^2.4.1". I don't see that version in the tags or releases. Not really sure what I'm getting.

**Comment by mjsalinger** [comment]
v3 is released and I fixed the tags to point to the proper commits for the old 2.x versions.  2.x will continue to be supported for bug fixes and community patches under the `2.x` branch, `master` is now pointed to the official `v3` branch.
