### ISSUE TITLE
Remove Wiki

### ISSUE THREAD

**Issue by neuquino** [oauthjs/node-oauth2-server#397]
If Docs are on ReadTheDocs, **the Wiki should be removed or kept updated**, because is confusing.

[Model-specification](https://github.com/oauthjs/node-oauth2-server/wiki/Model-specification) differs from [Server-options](https://github.com/oauthjs/node-oauth2-server/wiki/Server-options) in the way they instantiate the server (even the module name is different).

**Comment by maxtruxa** [comment]
Wiki was cleared out and [the landing page](https://github.com/oauthjs/node-oauth2-server/wiki) points to the docs.
