### ISSUE TITLE
Sending the user id or object back in the access token response?

### ISSUE THREAD

**Issue by JonathanBristow** [oauthjs/node-oauth2-server#399]
As per the title, how can I do this?

**Comment by komikoni** [comment]
I have the same question. 
I am wondering if updateResponse of AuthenticateHandler.js can be extended or externally implemented. 
Please let me know if there is another way to fill it in requestobject.

**Comment by maxtruxa** [comment]
This is described in the documentation of [model.saveToken()](http://oauth2-server.readthedocs.io/en/latest/model/spec.html#model-savetoken) as well as [OAuth2Server#token()](http://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#oauth2server-token).

Basically, all you need to do is to enable the `allowExtendedTokenAttributes` server option:

```
const oauth2 = new OAuth2Server({
  // ...
  allowExtendedTokenAttributes: true
});
```

This allows you to return additional properties from `model.saveToken()` which will be included in the token response:

```
model.saveToken = function saveToken(token, client, user) {
  // ...
  return {
    // ...
    user_id: user.id
  };
};
```

**Comment by JonathanBristow** [comment]
@maxtruxa I've tried enabling`allowExtendedTokenAttributes` but that includes loads of other stuff in the token. Do you have or know of a full example which returns the user id?

Thanks for your help!

**Comment by maxtruxa** [comment]
@JonathanBristow What exactly do you mean by "loads of other stuff"? There shouldn't be anything included except for what you return from `model.saveToken()`.

**Comment by JonathanBristow** [comment]
@maxtruxa Sorry I should have been a bit more descriptive. I've run some tests this evening and get back to you. I suspect I'm doing something obvious wrong so may be a false alarm.
Thanks for your links though, I've had a look at they help.

**Comment by komikoni** [comment]
I understand that allowExtendedTokenAttributes is a switch on whether to grant additional attributes to Tokens issued to OAuth clients.

This ISSUE discusses how to acquire User information linked to the Token acquired when Token's validity is confirmed after receiving the API request after the issue of Token by subsequent processing.
For example, it is about how to implement an API that acquires DB information on an end user basis linked to Token.
(In updateResponse, Scope can be acquired by embedding it in Reqest object, but User.Id etc can not be obtained)
