### ISSUE TITLE
Invalid param client_key error even with requireClientAuthentication.password disabled for Auth header

### ISSUE THREAD

**Issue by robertjustjones** [oauthjs/node-oauth2-server#403]
When the new `requireClientAuthentication.password: false` option is used (#346) to turn off client_secret, I'm getting an error on the `is.vschar()` check that has a regex requiring at least one char.  How is #346 and #377 being used by others?

**Comment by robertjustjones** [comment]
ok, the trouble occurs only when using the Authenticate method for credentials.  Editing title.

**Comment by maxtruxa** [comment]
Good catch! #404 was merged.
