### ISSUE TITLE
Access Token response formatting

### ISSUE THREAD

**Issue by cirick** [oauthjs/node-oauth2-server#405]
The `TokenModel` is returning the access token and other parameters in the response object as camel case. It seems from the [spec](https://tools.ietf.org/html/rfc6749.html#section-4.1.4) that everything is using underscores, the clients I'm using expect it as underscores, and this module itself expects underscores for input formatting like redirect_uri and access_token. I can convert it in my own route handler, but seems like it should be the default. Let me know if I'm missing something or this is on purpose. 

This is for v3.
```javascript
function TokenModel(data, options) {
  if (!data.accessToken) {
    throw new InvalidArgumentError('Missing parameter: `accessToken`');
  }
  this.accessToken = data.accessToken;
}
```

**Comment by maxtruxa** [comment]
@cirick The key names are translated to underscores later on in [`BearerTokenType#valueOf()`](https://github.com/oauthjs/node-oauth2-server/blob/master/lib/token-types/bearer-token-type.js).

**Comment by cirick** [comment]
@maxtruxa Thanks for the info. I was using the TokenHandler response as the body of the express result. Looking at where the BearerTokenType you mentioned is used I can see it modifies the response directly, and I shouldn't be using the TokenHandler response.

**Comment by lewma** [comment]
@cirick I'm having the exact same issue with response formatting.  How exactly did you fix your problem ?
