### ISSUE TITLE
Authorization code flow wrong ?

### ISSUE THREAD

**Issue by jackieju** [oauthjs/node-oauth2-server#407]
Hi,
I am trying implement full oauth2 provider based on this great repo.
But when I tried the authorization flow, I tested on postman:
http://localhost:3000/authorise?response_type=code&client_id=democlient&redirect_uri=http://localhost/cb&state=teststate&scope=profile
and got return:
{
  "statusCode": 401,
  "status": 401,
  "code": 401,
  "message": "Invalid token: access token is invalid",
  "name": "invalid_token"
}
The error is caused by authorize_handler.js line 89: this.getUser(request, response), which will check token.
Why check access toke at this step ?
As my understanding, the code flow has following steps:
1. Client call http://<oauth2_provider>/authorise?response_type=code... and rediect to login page
2. After login successfully, oauth2 provider redirect client(browser) to callback_url with authorization code
e.g. http://example.com/cb?code=xxxxx
3. Client call http://<oauth2_provider>/authorise?code=xxxxx&grant_type=authorization_code&client_id=xxxxx&
client_secret=xxxxx&redirect_uri=xxxxxx
4. oauth2 provider return access token in json 

I am not sure which step AuthorizeHandler.prototype.handle  should be invoked.
But seems access token shouldn't be checked in any step above ...

Please correct me if I am wrong.
And Please help me on this issue.

Thanks a lot !

Jackie

**Comment by maxtruxa** [comment]
@jackieju You have to specify the `authenticateHandler` server option, as described in the remarks of [`OAuth2Server#authorize`](http://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#oauth2server-authorize). Let me know if you get it to work.

**Comment by jackieju** [comment]
Hi maxtruxa,

Thank you for you reply. I used workaround to make it work by changing the code of Authorize-handler.getUser(). But after reading docs you provided, I think your way is better.

Thanks a lot.
Jackie

**Comment by maxtruxa** [comment]
Sounds like issue was resolved. Please re-open if something is still unclear.

**Comment by isgalt** [comment]
I have problem of Authorization code flow. I want auth code but its getting me access token,
