### ISSUE TITLE
TypeError: options.headers.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by runfan** [oauthjs/node-oauth2-server#413]
``` javascript 
new Response(ctx.response)
```
``` log
nodejs.TypeError: options.headers.hasOwnProperty is not a function
    at new Response (/Users/cwfan/code/outbook/outbook-api-v2/node_modules/oauth2-server/lib/response.js:16:25)
    at /Users/cwfan/code/outbook/outbook-api-v2/app/middleware/oauth2_token.js:11:22

```

**Comment by cirick** [comment]
Is the ctx.response you are passing formatted correctly based on the docs? (https://oauth2-server.readthedocs.io/en/latest/api/response.html) What is the format of ctx.response.headers?

**Comment by runfan** [comment]
ctx.response is replaced by other code

**Comment by paivaric** [comment]
I have same issue using koa2... how you solved it?

**Comment by willin** [comment]
koa 2.5 

node_modules/oauth2-server/lib/response.js:16:25
