### ISSUE TITLE
Why not update in npm?

### ISSUE THREAD

**Issue by renanbastos93** [oauthjs/node-oauth2-server#414]
On npm package this version 2.4, but in github version 3.x

**Comment by Luomusha** [comment]
+1,and how to install 3x?

**Comment by runfan** [comment]
npm install oauth2-server@^3.0.0-b1

**Comment by renanbastos93** [comment]
I using only `npm install oauth2-server --save` . because it install version 2.4.x? Is necessary update on npm package, it's okay?

**Comment by runfan** [comment]
3x is not a stable version, if you do not need to use the new features, it is best not to upgrade

**Comment by renanbastos93** [comment]
thanks @runfan , now understand.
