### ISSUE TITLE
Missing parameter for promisify call in AuthorizeHandler.prototype.generateAuthorizationCode 

### ISSUE THREAD

**Issue by kryysler** [oauthjs/node-oauth2-server#435]
The numArgs option for promisify is missing in https://github.com/oauthjs/node-oauth2-server/blob/master/lib/handlers/authorize-handler.js#L138

Causes execution timeout at least when used in a Serverless environment.

**Comment by maxtruxa** [comment]
There's already a PR fixing this issue. See #431.

**Comment by thomseddon** [comment]
Happy to say this has been fixed in 46bc95e1feb556e06ed6cd0f85821708d1f201a2 and released in 3.1.0
