### ISSUE TITLE
OpenID Connect 1.0 implementation ? Any plans ? 🆔

### ISSUE THREAD

**Issue by myuseringithub** [oauthjs/node-oauth2-server#437]
"node-oauth2-server" is dynamic and database agnostic, with ability to add custom grant types. Wish there was an OpenID Connect implementation for Node JS with the same extensibility. Could you add support for OpenID Connect specs, allowing authorization and authentication.

**Comment by markstos** [comment]
@myuseringithub Have you checked out the [oidc-provider](https://github.com/panva/node-oidc-provider) project?

**Comment by myuseringithub** [comment]
I'm currently using 'node-oidc-provider', the way 'node-oauth2-server' is configured, I feel, is much more extensible you have control over the middlewares. But with 'node-oidc-provider' the koa server is created by the framework and you have to extend through the framework's API, not my favorite. It took me a lot of time, digging through the documentation and source code to understand how the framework works. 
Thanks @markstos

**Comment by markstos** [comment]
@myuseringithub My experience has been similar. I tried `oidc-provider` as a OAuth 2 server, but found it complex to adapt. So, I'm back looking at `oauth2-server` as a simpler solution.
