### ISSUE TITLE
Auth code model example for mongo

### ISSUE THREAD

**Issue by ghost** [oauthjs/node-oauth2-server#44]
Please add example auth code of expressjs, mongodb. Models, routes

**Comment by pashtika** [comment]
Hello, 
What should we use for the following class to support for MongoDB?

	<bean id="clientDetails" class="org.springframework.security.oauth2.provider.client.JdbcClientDetailsService">
		<constructor-arg index="0">
			
			<ref bean="mongoTemplate" />
		</constructor-arg>
	</bean>

**Comment by thomseddon** [comment]
I think you might have the wrong module!

**Comment by manjeshpv** [comment]
@ghost https://github.com/slavab89/oauth2-server-example-mongodb/blob/master/model.js
