### ISSUE TITLE
How to get user info after authenticate() in v3.0?

### ISSUE THREAD

**Issue by troyeagle** [oauthjs/node-oauth2-server#442]
Env: NodeJS 7.9, Egg.js
In ver2, `getAccessToken` would callback and pass parameter `user` or `userid` ,which can be access through `req.user.id` (in egg.js, it is `ctx.request.user.id`).
But in v3.0, the document says token.client and token.user can carry additional properties that will be ignored by oauth2-server. So how can I get user info in v3.0 after authentication?

In Egg.js, I cannot get context object in model file. I have tried saving user info in oauth model getAccessToken() by `Application.createAnonymousContext()` but it seems not work.

Thanks.
Troyeagle

**Comment by yusufsyaifudin** [comment]
As documented here https://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#authenticate-request-response-options-callback and already answered in https://github.com/oauthjs/node-oauth2-server/issues/349 and https://github.com/oauthjs/node-oauth2-server/issues/327 you can obtain user info using `res.locals.oauth.token.user`
Example:

```
const userId = res.locals.oauth.token.user.id;
// get user using Bookshelfjs for example
const user = await User.where({ id: userId }).fetchFull();
```
