### ISSUE TITLE
How can i prevent to send error message response? v3

### ISSUE THREAD

**Issue by je3f0o** [oauthjs/node-oauth2-server#447]
Hey, this is my very first oauth server dev.
I just figured out and implemented models.
But when I try to invalid request, server responding error stack trace.
I dont want to leak information. How can i handle this proper way?
Thank you.

**Comment by maxtruxa** [comment]
Are you using express? If that's the case the default error handler is just dumping the stack trace to the client. You would have to add your own error handlers as described [in the documentation](http://expressjs.com/en/guide/error-handling.html).

Note that you don't have to do any of this yourself (provided you're really using express). You can just use our express adapter [`express-oauth-server`](https://npmjs.org/package/express-oauth-server).

**Comment by je3f0o** [comment]
Ok I got it. thank you.
