### ISSUE TITLE
ServerError is 503 instead of 500

### ISSUE THREAD

**Issue by MartinLoeper** [oauthjs/node-oauth2-server#461]
The server_error which is defined [here](https://github.com/oauthjs/node-oauth2-server/blob/e1f741fdad191ee47e7764b80a8403c1ea2804d4/lib/errors/server-error.js#L21) should yield status code 500, but there's 503 instead.

This causes friction in our environment since the outh server returns status code 503 if the refresh token is invalid: `{"error":"server_error","error_description":"invalid signature"}`.  
IMHO, 500 is more appropriate here. What do you think?

**Comment by mjsalinger** [comment]
I agree, that should be 500.  Will be a breaking change though so will require a major version update.  Can you submit a PR?

**Comment by thomseddon** [comment]
Continued in #472
