### ISSUE TITLE
Did this modules support openID?

### ISSUE THREAD

**Issue by duncup** [oauthjs/node-oauth2-server#467]
Some like the title.

**Comment by mjsalinger** [comment]
Not officially, but it's possible by including custom token attributes and creating your own JWT token.  We plan on implementing openid support natively in a future release.

**Comment by duncup** [comment]
Any help from here?I never done this before.

**Comment by nekman** [comment]
> Not officially, but it's possible by including custom token attributes and creating your own JWT token. We plan on implementing openid support natively in a future release.

Hi, starting this old thread again. We are using this library to support OAuth and it works great, really nice and well written library. Regarding openid, do you still have any plans to support this? Or do you have any examples how we can implement our custom token attributes for the ID token?
