### ISSUE TITLE
How to verify token and authorise routes are working?

### ISSUE THREAD

**Issue by cesine** [oauthjs/node-oauth2-server#47]
I'm trying to see if i got the postgres example working.
## Verify user creation

(based on the tests)

``` bash
$ curl http://127.0.0.1:3000/oauth/token --request POST --data  '{"grant_type": "password", "client_id": "thom", "client_secret": "nightworld", "username": "thomseddon", "password": "nightworld"}' --header "Content-Type: application/x-www-form-urlencoded"
#{
# "code": 400,
# "error": "invalid_request",
# "error_description": "Invalid or missing grant_type parameter"
#}
```
## Verify user authorization

(based on the tests)

``` bash
$ curl http://127.0.0.1:3000/oauth/authorise --request POST --data  "{response_type: 'code', client_id: 'thom', redirect_uri: 'http://nightworld.com'}" --header "Content-Type: application/x-www-form-urlencoded"
# TypeError: Cannot read property 'user' of undefined
# ln:20  if (!req.session.user) {

```

**Comment by gjoforte** [comment]
Hi,

I used your postgres example and converted it to sqlite. I've managed to get an **access_token**: {"token_type":"bearer","access_token":"914760c1a1c05227a7ff903e4451692ae2fa23df","expires_in":3600} with the following request: **POST 127.0.0.1:3000/oauth/token**. 

But now when I try: **GET 127.0.0.1:3000/oauth/authorise?grant_type=password&username=gjoforte&password=123qwe** 

I get the same error cesine was getting:
```
# TypeError: Cannot read property 'user' of undefined
# ln:20  if (!req.session.user) {
```
Btw, I'm using JMeter to perform my HTTP requests.

**Comment by chris9r** [comment]
`# TypeError: Cannot read property 'user' of undefined
# ln:20  if (!req.session.user) {`

This happened to me as I wasn't using the cookie-parser and the cookie-session modules. In my example code these modules are part of express, but for now they are standalones which you have to install separately.

**Comment by maxtruxa** [comment]
v3 doesn't touch the `session` object. If you're using `express-oauth-server` the `user` and `client` objects are available through `res.locals.oauth.token` as `res.locals.oauth.token.user` and `res.locals.oauth.token.client`, respectively.
See #349 and #327.

**Comment by chris9r** [comment]
I'm using 2.4.1.

'OAuth2Error: Invalid client credentials'

Do you know why I'm getting this error?

The parameters passed to the getClient function of my model don't seem to be correct. The console.log() output shows the following:

`#{client_id}`
`null`
`[Function]`

And my code:

```
OAuthClientsSchema.statics.getClient = function(clientId, clientSecret, callback) {
    console.log(clientId);
    console.log(clientSecret);
    console.log(callback);
  var params = { clientId: clientId };
  if (clientSecret != null) {
    params.clientSecret = clientSecret;
  }
  OAuthClientsModel.findOne(params, callback);
};
```
