### ISSUE TITLE
response.redirect not working

### ISSUE THREAD

**Issue by arihantdaga** [oauthjs/node-oauth2-server#470]
I am using express 4. 
I am stuck at something for a long time..
But i think this is a bug, 
response.redirect is not working.. 

I tried using the code below.. 

```
app.post('/auth', awkard, (req,res)=>{
    // res.redirect("http://localhost:3002/api");      // IT DOES WORK
    var request = new Request(req);
    var response = new Response(res);
    response.redirect("http://google.com");          // IT DOES NOT WORK
```

Hence in AuthorizeHandler.prototype.updateResponse after generating auth_code it's not redirecting to the redirect_uri.

**Comment by maxtruxa** [comment]
`Response#redirect` only marks the response as a redirect (i.e. it tells whoever actually sends the response that a request *should* happen). It doesn't send anything by itself.

If you're using this module without [one of the available wrappers](http://oauth2-server.readthedocs.io/en/latest/docs/adapters.html) you'll have to handle this case yourself. If you really want or have to roll your own adapter, check out how [`express-oauth-server`](https://github.com/oauthjs/express-oauth-server) is implemented, specifically [`handleResponse`](https://github.com/oauthjs/express-oauth-server/blob/38811599924a27132fcddfc5625c310b251aea11/index.js#L133).
