### ISSUE TITLE
Support for continuation-local-storage

### ISSUE THREAD

**Issue by bozzltron** [oauthjs/node-oauth2-server#479]
Hello.  I am looking for options on using continuation-local-storage with this module. My use case is that I am establishing a namespace for each request.  I would then like to update that namespace with new information from the model implementation.  Currently, the context is lost when I try to grab my established namespace from within model.  

Thank you.

**Comment by MartinLoeper** [comment]
Is this an issue with node-oauth2-server or cls?   
We use node-oauth2-server in conjunction with [https://www.npmjs.com/package/express-http-context](express-http-context) and it works well!

Please note: latest nodejs version and the troubleshooting section at the page linked above.

**Comment by nekman** [comment]
slightly off topic: Using it with `async_hooks` and it works good (I have never got the cls to work on our environment). Checkout https://www.npmjs.com/package/async-local-storage

**Comment by bozzltron** [comment]
http-context is exactly what I needed.  I didn't realize that if gave you access to the context apart from the req object.  Really really nice.
