### ISSUE TITLE
Scopes aren't assigned to Tokens

### ISSUE THREAD

**Issue by nullpixel** [oauthjs/node-oauth2-server#497]
Hey,

I've noticed an issue where tokens do not have a scope:

```ts
    verifyScope: async (token: OAuth2Server.Token, scope: string): Promise<boolean> => {
       console.log(token.scope) // null
    }
```

I initially thought this was my fault, but I've checked and my auth code table does have the scope in it.
`"e072c0e3cb851255729a8f1320db6b6e923de7c0","profile","http://localhost:3000/callback","2018-05-30 12:00:07.958",t,"54141054177247232","EBCD7D156417EECF67E11E1C21A99C4E"` (profile)

I've looked in the code to see if the scope is actually ever set on the token, and I can't find where this happens, leading me to believe it doesn't.

**Comment by nullpixel** [comment]
cc/ @razvanz because you've made some scope-related fixes on dev, which may fix this.

**Comment by razvanz** [comment]
What `grant_type` did you used to obtain the token?
Can you provide a minimal example reproducing the issue?

**Comment by nullpixel** [comment]
Yeah, I'll make one in a bit.

I used `authorization_code`

**Comment by nullpixel** [comment]
Sorry, this was my bad.
