### ISSUE TITLE
getAccessTokenExpiresAt doesn't work

### ISSUE THREAD

**Issue by xlc** [oauthjs/node-oauth2-server#507]
https://github.com/oauthjs/node-oauth2-server/blob/e1f741fdad191ee47e7764b80a8403c1ea2804d4/lib/grant-types/abstract-grant-type.js#L72

[Date.setSeconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setSeconds) only set the seconds part of the date.
The correct code should be `new Date(Date.now() + this.accessTokenLifetime * 1000)`

Similar issue exists for `getRefreshTokenExpiresAt`

**Comment by maxtruxa** [comment]
This was already fixed by #444 which has been merged into dev. I'll try to get some pending PRs merged and push a new master soon.
