### ISSUE TITLE
Branch Plan

### ISSUE THREAD

**Issue by thomseddon** [oauthjs/node-oauth2-server#512]
@mjsalinger So we're on the same page, I've been merging into master but I now see it looks like you've been working in dev.

Apologies for this I hadn't noticed.

I'm thinking we make a breaking 3.1.x release quite soon with the updated packages and any quick PRs we can merge?

**Comment by thomseddon** [comment]
I have merged the current master into dev, happy to use this branch for future merges and keep master stable if this is proffered

**Comment by mjsalinger** [comment]
I could go either way on the dev vs master branch..  It was suggested by some other members.  

I'm on vacation currently, was planning on releasing a beta next week..  Should we really make 3.1.x breaking?  I tend to try to avoid breaking unless it's Semver-major...  I suggest once we get what we want merged in we release to as 3.1.0-beta.1 and in npm under the `next` tag, let it be used a bit before releasing 3.1.0 stable...

Welcome back!

**Comment by mjsalinger** [comment]
@thomseddon Looking at the change with the error code, since it's breaking I think we need to bump to 4.0.0.  If users are relying on SemVer in their CI builds, this could break downstream projects.

**Comment by thomseddon** [comment]
Yeah that makes sense, I think we should do a 3.0.1 release with the dependency bump and then probably pile everything else into 4?

**Comment by mjsalinger** [comment]
#496 Was asking about merging some of the fixes into a 3.1.0...  I think for this one time, we should release 4.x, and then maybe backport bug fixes (non-breaking) into 3.1.0.  So to summarize:

3.0.1 with just dependency changes
3.1.0 with any fixes and some non-breaking changes
4.x with the breaking change, drop support for node 4, and major changes.  I'll create some branches and start to stage these.  It's a bit of a pain but I think it's the right thing to do, then we can move forward with a better process going forward...

**Comment by mjsalinger** [comment]
Today I published two versions of node-oauth2-server:

3.0.1 contains dependency upgrades only
3.1.0-beta.1 installed under the next tag in npm, this contains a bunch of fixes and a couple of new features. Please submit any issues with this release as seperate issues, and we'll try to get a GA release in the next couple of weeks.

This will be the last 3.x branch release and last branch to support node 4.x . After this we'll turn attention to 4.0.0.

While this is in beta, I'll work to get the express wrapper in line with the new versions and tested.
