### ISSUE TITLE
Is this project really maintained?

### ISSUE THREAD

**Issue by wdalmut** [oauthjs/node-oauth2-server#521]
hi,

this project is really interesting but it seems to be no longer maintained, there are pull requests that are merged but those are not available via npm or in branch 3.x (like implicit flow).

any about this? Do you need any kind of help on this repository?

bests
Walter

**Comment by Doom100500** [comment]
In npm registry we still have 2.4.0 however.
How we can upgrade to just released 3.0.1 ?

**Comment by maxtruxa** [comment]
@Doom100500 Make sure you are using the correct name for the npm package. There were one or two "alternative" names which are *not* updated (anymore?). [`oauth2-server`](https://www.npmjs.com/package/oauth2-server) is the right one.
