### ISSUE TITLE
how to encrypt the response token

### ISSUE THREAD

**Issue by alukaa** [oauthjs/node-oauth2-server#543]
the response is like this, is any way to encrypt and decrypt the token use openssl or something like it
![image](https://user-images.githubusercontent.com/8164389/49335951-3fdccc80-f633-11e8-8728-3abf1b8c560c.png)

**Comment by rajinikumar** [comment]
Hi, I am trying to implement oauth .. could you please provide the same code with routing?

**Comment by alukaa** [comment]
i almost forgot this one, may shoube be like [this](https://github.com/thephpleague/oauth2-server)

**Comment by rajinikumar** [comment]
Thanks for your reply. Have any sample for using nodejs(express) and mongodb

**Comment by alukaa** [comment]
the screenshot is just a demo usibg this repo, but i found these are origin token, a use php version of oauth server that the token is encrypted, so i create this issue to ask if is there a way to encrypt the token,that's why.

**Comment by thomseddon** [comment]
The spec just requires the use of TLS: https://tools.ietf.org/html/rfc6750#section-5.2

>  To protect against token disclosure, confidentiality protection MUST be applied using TLS [RFC5246] with a ciphersuite that provides confidentiality and integrity protection.
