### ISSUE TITLE
When will 4.0 land?

### ISSUE THREAD

**Issue by ToonvanStrijp** [oauthjs/node-oauth2-server#549]
When will v4.0 of this library land? Cause I'm waiting... but I see a few months of inactivity and nothing get's updated that fast, maybe it's better if someone takes this library to the next level?

**Comment by flowersinthesand** [comment]
@joaogranado @lfk @maxtruxa @mjsalinger @ruimarinho @ruipenso @thomseddon

I have the same question. Is there any plan for 4.0?

**Comment by thomseddon** [comment]
Nobody is actively maintaining this library at the moment, if someone would like to step forward then I would be happy to allow add them as a collaborator following a few successful PRs

**Comment by ToonvanStrijp** [comment]
@thomseddon I would like to collaborate on this :)

**Comment by thomseddon** [comment]
That would be great, if you start submitting PRs, tag me in them so I can review & merge the first few?

**Comment by ToonvanStrijp** [comment]
Sure thing!

**Comment by sheltonial** [comment]
Any docs/checklist on what needs to be done before launching 4.0?

**Comment by thomseddon** [comment]
@sheltonial we're probably going to skip 4.0 now, we have 5.0 under development in #564
