### ISSUE TITLE
null clientSecret question

### ISSUE THREAD

**Issue by mahees-medullan** [oauthjs/node-oauth2-server#55]
Hello, 

Im a little new with OAuth2. Im not 100% clear on how to pass in a null clientSecret.

I noticed under getClient (clientId, clientSecret, callback) i can pass in string|null for clientSecret

However, i keep seeing this error "Missing client_secret parameter" when i try posting with this body
"grant_type=password&username=johndoe&password=A3ddj3w&client_id=spa"

I noticed this is from this line master/lib/grant.js:88

Im not sure exactly how to pass in a null client_secret. Can you kindly assist?

**Comment by synthecypher** [comment]
@thomasdashney is this still the desired behaviour given that another project from oauthjs group says that the `client_secret` presumably because the _client secret_ confidentiality is not guaranteed?

**Comment by maxtruxa** [comment]
@synthecypher With 3.x you can disable client authentication for selected grants through the [`requireClientAuthentication` server option](http://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#oauth2server-token).
