### ISSUE TITLE
Example for express routine

### ISSUE THREAD

**Issue by rajinikumar** [oauthjs/node-oauth2-server#551]
Hi, I am new to ouath workflow. I am trying to implement oauth in express with mongodb.. have any examples with routing workflow?

**Comment by mgara** [comment]
There is the https://github.com/oauthjs/express-oauth-server project that implements the oauth2 flow if you want to take a look at it.

**Comment by rajinikumar** [comment]
Thanks, I will check it.

**Comment by 14gasher** [comment]
@rajinikumar also, feel free to checkout https://github.com/14gasher/oauth-example for a working example of that
