### ISSUE TITLE
Invalid request content-type w/ AWS Lambda

### ISSUE THREAD

**Issue by DmiPet** [oauthjs/node-oauth2-server#569]
Hello! I'm attempting to set up oauth2-server with AWS Lambda, and am getting an error on calling token()

`"Invalid request: content must be application/x-www-form-urlencoded"`

Since there is no `req`, `res` with Lambda, I create the Request object as follows from `event`

`let req = new OAuth2Server.Request({
        method: event.httpMethod,
        query: event.queryStringParameters,
        headers: event.headers,
        body: event.body
});`

When I call `req.get('content-type')` I get `application/x-www-form-urlencoded`. But that doesn't prevent the error, it seems the issue is with the check at [token-handler.js:84](https://github.com/oauthjs/node-oauth2-server/blob/90d00495842cbc68869214a4e6696e5ad048c93d/lib/handlers/token-handler.js#L84).

I'm not sure if I'm doing something wrong here, any help would be appreciated!

Thanks in advance.

**Comment by DmiPet** [comment]
Pardon the short-lived issue, but after diving into type-is docs, realized the problem was that there were not `Content-Length` or `Transfer-Encoding` headers, causing the typeis to return as Null. Not sure why those headers weren't set by API Gateway/Lambda, but manually adding in `Content-Length` seems to have helped.

**Comment by kannan-cidc** [comment]
@DmiPet  for the details, I had the same problem and was banging my head, adding the content-length like you suggested solved the problem.
