### ISSUE TITLE
Submitting Express Authorization Code Grant Example - Docs, Code, and Explanations.

### ISSUE THREAD

**Issue by 14gasher** [oauthjs/node-oauth2-server#571]
Hey y'all,

I went through the source code line by line to figure this thing out for the authorization code grant flow.

Here is the result of my efforts with *hopefully* better documentation than the other examples:

https://github.com/14gasher/oauth-example

Hope this helps someone.

Asher

**Comment by WNemencha** [comment]
Thanks for the cool example, did help me ;)

**Comment by 14gasher** [comment]
Just updated the example with new test cases, better debugging statements, and a separation of client and auth server with forms.

**Comment by 14gasher** [comment]
Updated the example again. Now it includes details on how to implement initial user authentication as that is lacking from the library.

**Comment by thomseddon** [comment]
👍 added a note in the readme, thanks
