### ISSUE TITLE
Implement Automated Dependency Management

### ISSUE THREAD

**Issue by PatOnTheBack** [oauthjs/node-oauth2-server#573]
Implement an automated dependency management tool. This can make it easier to manage dependency updates and warn about security vulnerabilities in dependencies.
GitHub has a built in vulnerability scanner in the `Security` tab of this repository.

Another tool that this project could use is https://renovatebot.com/ to automatically create PRs to update dependencies.

**Comment by thomseddon** [comment]
👍 I've added renovatebot and will use this in v5
