### ISSUE TITLE
What happens if the refresh token is expired?

### ISSUE THREAD

**Issue by andrelandgraf** [oauthjs/node-oauth2-server#574]
We implemented the `getRefreshToken(refreshToken, [callback])`after the [specs](https://oauth2-server.readthedocs.io/en/latest/model/spec.html). Refreshing the access token with a valid refresh token works but if the refresh token is expired, we receive the following error.

When the refresh token is expired, the process stops after `getRefreshToken` and `getClient` is never been called. What should we return in `getRefreshToken` to trigger an Error case, e.g. notAuthorized for the user?

Thanks in advance for any support!

**Comment by andrelandgraf** [comment]
Nevermind, I am stupid.

**Comment by emjimadhu** [comment]
@andrelandgraf Did you find out the flow? I neeed some clarification too.

**Comment by andrelandgraf** [comment]
Hi @emjimadhu 

I think it was a bug on our end. I cannot remember entirely what the problem was, but maybe I think it had something todo with our getRefreshToken and revokeToken implementation.

Flow if refreshToken is valid, but access token has been expired:
```
2020-04-13T18:22:21.819Z [middlewares/oauth.js] debug: getAccessToken called
2020-04-13T18:22:22.332Z [controllers/auth.js] info: obtainToken called
2020-04-13T18:22:22.333Z [middlewares/oauth.js] debug: getClient-function called
2020-04-13T18:22:22.334Z [middlewares/oauth.js] debug: getRefreshToken called
2020-04-13T18:22:22.934Z [middlewares/oauth.js] debug: RevokeToken called
2020-04-13T18:22:23.418Z [middlewares/oauth.js] debug: saveToken-function called
```

Flow if both refresh and access token have been expired:
```
020-04-13T18:48:30.549Z [middlewares/oauth.js] debug: getAccessToken called
2020-04-13T18:48:30.907Z [controllers/auth.js] info: obtainToken called
2020-04-13T18:48:30.909Z [middlewares/oauth.js] debug: getClient-function called
2020-04-13T18:48:30.911Z [middlewares/oauth.js] debug: getRefreshToken called
2020-04-13T18:48:31.218Z [controllers/auth.js] warn: invalid_grant: Invalid grant: refresh token has expired
```

So if a refresh token expires, `oauth.token` will throw an error after the function `getRefreshToken` has been called. You can catch that error inside your function `obtainToken` . (This is where I `console.warn()`.) 

My obtainToken function:
```
const obtainToken = async (req, res) => {
  console.tag(TAG).info('obtainToken called');
  const request = new Request(req);
  const response = new Response(res);

  if (req.body.grant_type === 'password' && !req.body.password) {
    console.tag(TAG).error('no password found in body');
    return res.status(400).json({
      error: 'BadRequest',
      message: 'no password in req body',
    });
  }

  try {
    const token = await req.app.oauth.token(request, response);
    const returnToClient = {
      accessToken: token.accessToken,
      accessTokenExpiresAt: token.accessTokenExpiresAt,
      refreshToken: token.refreshToken,
      refreshTokenExpiresAt: token.refreshTokenExpiresAt,
      // password have been removed already
      user: token.user,
    };
    return res.status(200).json(returnToClient);
  } catch (err) {
    console.tag(TAG).warn(`${err.name}: ${err.message}`);
    return res.status(401).json({
      error: err.name,
      message: err.message,
    });
  } 
```

I hope this helps you figure out what to do if the request token expires. I just use the 401 code in my client to delete the refresh and access token and reroute the user to the login page.

**Comment by emjimadhu** [comment]
@andrelandgraf Wow!!! Thank you so much for this detailed explanattion. It helped me a lot. Thanks.a lot.
