### ISSUE TITLE
Typescript minimal example

### ISSUE THREAD

**Issue by cheatmenot** [oauthjs/node-oauth2-server#577]
Hello, I would like to ask for help because i'm doing my projects in typescript and I am having a hard time converting examples to typescript, can anyone send me link to examples that uses TS? I am currently at adding the oauthserver to my main app.ts, and I encounter errors on importing the models:

    this.app.oauth = oauthServer({
      model: model
    });

(node:15228) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'options' of undefined

**Comment by thomseddon** [comment]
Sorry I don't have an example for this, we will look to include typescript examples in v5 👍
