### ISSUE TITLE
Maintainer request

### ISSUE THREAD

**Issue by 14gasher** [oauthjs/node-oauth2-server#578]
@thomseddon I'd like to be added as part of the oauth team. I'll help keep this repo up to date, update the examples, and so on.

**Comment by cyruseftos** [comment]
+1 @thomseddon keen to jump in and help close some of these maintenance PRs that are open

**Comment by thomseddon** [comment]
@14gasher @cyruseftos we have now merged the rewrite into v5-dev, if you could jump into any open issues that would be a MASSIVE help.

Also, we're in need of documentation for the new branch, so please feel free to jump on that too! Any consistent contributor will be added as a collaborator :)
