### ISSUE TITLE
Issue with custom generateAuthorizationCode in model

### ISSUE THREAD

**Issue by singui91** [oauthjs/node-oauth2-server#580]
I tried passing in a custom generateAuthorizationCode in the model but it is not working. Did not continue with the library codes after return from my function. I tried with generateRefreshToken and generateAccessToken. Both functions are working. Seems like the code stop here in authorize-handler.js.

return this.generateAuthorizationCode(client, user, scope);
	})
        .then(function(authorizationCode) {
          state = this.getState(request);
          ResponseType = this.getResponseType(request);

          return this.saveAuthorizationCode(authorizationCode, expiresAt, scope, client, uri, user);
        })

**Comment by thomseddon** [comment]
This should work, there's a test that seems to check this is correctly invoked.

If this is still a problem, please just re-open this issue with a minimal code sample that shows the problem

**Comment by singui91** [comment]
line 138 in node-oauth2-server/lib/handlers/authorize-handler.js should change to 
return promisify(this.model.generateAuthorizationCode, 3).call(this.model, client, user, scope);
to fix the issue

**Comment by jackdon** [comment]
> line 138 in node-oauth2-server/lib/handlers/authorize-handler.js should change to
> return promisify(this.model.generateAuthorizationCode, 3).call(this.model, client, user, scope);
> to fix the issue

Thanks, this fix solved my problem.
