### ISSUE TITLE
How to revoke or delete the token, I need to do this when i logged out?

### ISSUE THREAD

**Issue by p-g-krish** [oauthjs/node-oauth2-server#582]
I refer this [https://oauth2-server.readthedocs.io/en/latest/model/spec.html#revoketoken-token-callback](url) in Documentation. I want to implement this in express, based on express implementation guidance i tried like this application.oauth.revokeToken(mytoken). But it's return revokeToken is not a function. Can u guide me to solve this problem

**Comment by vankien96** [comment]
When user calls logout you can get accessToken from header and delete it in the database.

**Comment by p-g-krish** [comment]
Thanks for the idea, It's working.
