### ISSUE TITLE
Question: Should Access Tokens be encrypted ?

### ISSUE THREAD

**Issue by Igor-Lopes** [oauthjs/node-oauth2-server#585]
It's not clear in the documentation if `Access Tokens` should be encrypted. It appears to me if they're stored raw in the database, it would be a security issue. 

Should I encrypt `Access Tokens` ?

What algorithm should be used to encrypt them ? RSA with public/private keys ?

**Comment by thomseddon** [comment]
I don't believe the spec specifies requirements for at-rest storage, only that it must be encrypted in transit, from https://tools.ietf.org/html/rfc6750#section-5.2:

> To protect against token disclosure, confidentiality protection MUST be applied using TLS [RFC5246] with a ciphersuite that provides confidentiality and integrity protection.

I know some providers hash them (hence why you can't ever see them twice) and some don't, it's up to you :)

**Comment by Igor-Lopes** [comment]
Thank you for your response !

**Comment by kehers** [comment]
From a security perspective, I will argue that access tokens should be encrypted in the DB. I just started looking at the library, but one idea I figure can work is this:
1. In `generateAccessToken`, generate a JWT token that will be an object containing a unique id and a token string. This will be our access token.
2. In `saveToken` decrypt the JWT token (token.accessToken) to the id and token. Store the id and an encrypted version of the token.
3. In `getAccessToken`, decrypt as above and use the id to get the saved token from the DB

I will implement this and update with status of test.
