### ISSUE TITLE
Invalid token fields

### ISSUE THREAD

**Issue by lewma** [oauthjs/node-oauth2-server#586]
Hello

I'm having a hard time getting the tokens generated by this project to be compatible with swagger.  It turns out that the token fields generated are not compatible.  For example, accessToken needs to be access_token for swagger to operate correctly.  How can this be configured ?

thanks!

**Comment by lewma** [comment]
Ignore this comment.  I was using the wrong Response object returned by the library.

**Comment by aeri** [comment]
That's right, it's not following the standard for returning the answer. It should be "access_token" and not "accessToken". This causes it not to be compatible with either Insomnia or Postman using oAuth
