### ISSUE TITLE
promisify of generateAuthorizationCode broken

### ISSUE THREAD

**Issue by bgaspic** [oauthjs/node-oauth2-server#600]
Hi,

lib/handlers/authorize-handler.js :138 needs to change from
`    return promisify(this.model.generateAuthorizationCode).call(this.model, client, user, scope);`
to
`    return promisify(this.model.generateAuthorizationCode, 3).call(this.model, client, user, scope);`
 
without that, the middleware just hangs when model.generateAuthorizationCode is provided.

Thanks
Boris

**Comment by bgaspic** [comment]
Actually, after further digging I found that a commit already addresses this issue -- the 
[431](https://github.com/oauthjs/node-oauth2-server/pull/431/commits/74a4b14fd3e0ad21e7d2325f92d1980f169f692a) -- but it's not fixed in the 3.0.0 oauth2-server whom npm pulled.

When could that commit become deployed?

**Comment by thomseddon** [comment]
This will be released in 3.1.0, very shortly
