### ISSUE TITLE
Generate new refresh token when refresh token has expired?

### ISSUE THREAD

**Issue by emjimadhu** [oauthjs/node-oauth2-server#607]
As far as i can understand, so far we can generate new refresh token if the old refresh oken is valid. And if its expired, it is sending a 400 error. Instead i want to generate a new refresh token and seend back instead of 400. How can i achieve this?

**Comment by SAprelov** [comment]
Is it secure?

**Comment by emjimadhu** [comment]
@SAprelov I dont know. I am trying to find what would be he best case.

**Comment by SAprelov** [comment]
I believe 401 is fine. User must reauth.

**Comment by emjimadhu** [comment]
@SAprelov I understood the whole refresh token flow by reading actual oauth specification. Thank you omuch.
