### ISSUE TITLE
Why revokeAuthorizationGrant method getting called everytime?

### ISSUE THREAD

**Issue by emjimadhu** [oauthjs/node-oauth2-server#612]
I just dont understand a flow of `authorization_code`.

Following are the methods i have on mongo model

- getClient
- saveAuthorizationCode
- getAuthorizationCode
- revokeAuthorizationCode
- saveToken
- getAccessToken
- getRefreshToken
- revokeToken
- verifyScope

In `revoke*` mongo model meethods i am setting a old date just like in express example of this repo.

I have implemented both `authorization_code` and `refresh_token`. 

And this is how i trigger the auth flow

1) curl --location --request POST 'http://localhost:3000/oauth/authorize?client_id=nwClient&response_type=code&user_id=some-user-id&state=test&redirect_uri=redirect-uri/&scope=*' \
--header 'Content-Type: application/x-www-form-urlencoded'

I am getting the following output
```
...
"authorizationCode": "auth code",
"expiresAt": "auth code exiration date",
```

2) `curl --location --request POST 'http://localhost:3000/oauth/token' \
--header 'Authorization: Basic base64-of-client-credentials' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'code=auh-code'`

and i am getting

```
{
    "access_token": "access-token",
    "expires_in": "access-token-expires",
    "refresh_token": "refresh-token",
    "refresh_token_expires_in": "refresh-token-expires",
    "token_type": "bearer"
}
```

Whenever i hit this url for generaating new access_token, it triggers `revokeAuthorizationCode` method and which inturn makes my auth_code expired!

Why is this behaviour? I am hitting this url, to get a new access token when it expired! But it is making my auth code expired. Is this the default behaviour? Or am i doing something wrong?

**Comment by SAprelov** [comment]
Is that RFC non compliant?

**Comment by emjimadhu** [comment]
@SAprelov Hi, sorry i didn't know the exact RFC compliant for this. Now i read the RFC and understood, it is the intened behavour.

 https://tools.ietf.org/html/rfc6749#page-25 page 25 and 26. Point 4.1.2. To summarize
- The authorization code MUST expire shortly after it is issued to mitigate the risk of leaks.  A maximum authorization code lifetime of 10 minutes is RECOMMENDED.
- The client MUST NOT use the authorization code more than once.  If an authorization code is used more than once, the authorization server MUST deny the request and SHOULD revoke (when possible) all tokens previously issued based on that authorization code.

Thanks. and closing this issue.
