### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by JrSchild** [oauthjs/node-oauth2-server#62]
I am receiving a 500 Internal Server Error every time authentication fails. With in the body of the response an uncorrectly formatted json. The keys should have single quotes around them and the status in the header should be set correctly.

```
{
  code: 400,
  error: 'invalid_grant',
  error_description: 'User credentials are invalid',
  stack: undefined
}
```

I am not exactly sure why, but I think it has something to do with how the error is thrown. For instance in usePasswordGrant() the done function is called with the error object. This also throws a Server Error in my case even though it's not really a server error.

A nice solution for me was to send this object to the client. In the runner.js file I changed line 16 from:
`if (err || pos === last) return next(err);`
to:

```
if (err) {
  if (err.headers) context.res.set(err.headers);
  return context.res.json(err.code, err);
}
if (pos === last) return next();
```

This way the error gets send back to the client like it should (in my opinion). The changes I made are [in my fork](https://github.com/JrSchild/node-oauth2-server/commits/master).

Thoughts?

**Comment by nickmarx12345678** [comment]
I'm having this issue as well
