### ISSUE TITLE
Bug generateAuthorizationCode

### ISSUE THREAD

**Issue by ltduc** [oauthjs/node-oauth2-server#625]
Hi, Team!

When NodeJS i implement model generateAuthorizationCode Then bug:
generateAuthorizationCode: (client, user, scope) => {
    log({
      title: 'Generate Authorization Code',
      parameters: [
        { name: 'client', value: client },
        { name: 'user', value: user },
      ],
    })

    const seed = crypto.randomBytes(256)
    const code = crypto
      .createHash('sha1')
      .update(seed)
      .digest('hex')

    return code
  }

**Comment by desaijay315** [comment]
Please attach the errors here

**Comment by thomseddon** [comment]
Happy to say this has been fixed in 46bc95e1feb556e06ed6cd0f85821708d1f201a2 and released in 3.1.0
