### ISSUE TITLE
Node oauth2 server : Tokens invalidated after Oauth2 restart

### ISSUE THREAD

**Issue by darshankaarki** [oauthjs/node-oauth2-server#633]
We have implemented oauth2-server in our node APIs and all requests to APIs are secured using oauth password grant. 

We provided access token and refresh token to the client for accessing our API endpoints. The tokens have long expiration times.

Whenever our APIs including the Oauth endpoint is restarted , all tokens provided to clients get invalidated and we start getting 400 and 401 responses from oauth endpoints.

Is there a way to stope this behaviour? 
I initially thought that as the tokens are self contained , restating our Oauth endpoints will not invalidate the issued tokens.

This behaviour is causing the clients being signed out even when access and refresh tokens have not expired.

Please help.

**Comment by jaipreet-chhatwal** [comment]
Hi Darshan,

What sort of token are we talking about?.
JWT or Reference tokens. Either way, restarting the server should not
impact the token to be expired as ,

 For JWT tokens to be invalid, either the       signature validation can
fail or the token itself   has expired

 For Reference tokens, tokens will not be available in the DB or they have
expired.

What I am trying to point is, if restarting the server is causing issues
definitely the token verification code (how token in internally verified)
is having some issues.


Hope this helps.

Regards
Jaipreet

**Comment by darshankaarki** [comment]
Thanks Jaipreet.

I am not sure if the tokens is reference or JWT. We are using the oauth2-server library with grant type "password".

We are not storing the tokens anywhere in DB. 

We get the below response from "app.oauth.token" function in the below form:

accessToken:
accessTokenExpiry:
refreshToken:
refreshTokenExpiry:

And use "app.oauth.authenticate" function to authenticate these tokens. Every thing works fin until we restart our oauth2-server service.

Please advise and let me know if any other details are required. Thanks for your help.

**Comment by thomseddon** [comment]
Hi,

The idea of this library is that you supply a "model" which you use to persist the tokens in a database.

These are the methods you'd need to implement to use the "password" grant type: https://oauth2-server.readthedocs.io/en/latest/model/overview.html#password-grant

I understand the documentation isn't brilliantly clear in some places, which is something we're working on improving.

**Comment by darshankaarki** [comment]
Thanks Thom for your response.
I had also deduced based on other information available on this repo.

I was of the view that the tokens are self contained therefore restring the oauth service would not impact it.

One follow-up question though-as I am planning to try the redis implementation . Can you help me understand as redis is also a in memory datastore, will we be able to circumvent this issue using redis implementation? 

As in such case we will be saving the token in redis. Does restarting our Oauth service affect redis data?

**Comment by darshankaarki** [comment]
Closing this as there is no way out of this other than persisting tokens.

I have decided to go with a KWT token implementation instead of Oauth
