### ISSUE TITLE
Using email as username

### ISSUE THREAD

**Issue by oklas** [oauthjs/node-oauth2-server#682]
How about to allow auth using an email? Currently the [verifications](https://github.com/oauthjs/node-oauth2-server/blob/v3.1.1/lib/grant-types/password-grant-type.js#L83) of an username in the password grant type does not allows a valid email symbols. The [validator](https://github.com/oauthjs/node-oauth2-server/blob/v3.1.1/lib/validator/is.js) have no such verifications.

**Comment by whatwewant** [comment]
Just to validate email in your `getUser` model

**Comment by whatwewant** [comment]
Like this

```
async getUser(username, password) {
  if (!is.email(username)) {
    throw new InvalidRequestError('Invalid email')
  }
 // ...    
}
```

**Comment by oklas** [comment]
There is not a question how to check email in user code. The question is `oauth2-server`does not allow emails as user name. I mentioned above link to code wich verify username. That verification forbid emails.

**Comment by oklas** [comment]
There is not a question how to check email in user code. The question is `oauth2-server`does not allows emails as user name. I mentioned above link to code wich verify username. That verification forbid emails.

**Comment by whatwewant** [comment]
https://github.com/oauthjs/node-oauth2-server/blob/0bbdcfeaaf0d73e06acc028cd0d009eafab70817/lib/grant-types/password-grant-type.js#L83
https://github.com/oauthjs/node-oauth2-server/blob/0bbdcfeaaf0d73e06acc028cd0d009eafab70817/lib/validator/is.js#L59
the code here is only to check

**Comment by oklas** [comment]
Hm. There was some strange problem when I created this issue - when specifying an email, the test crashed with an `InvalidRequestError` exception from this location. Now I tried it and it's not reproducing any more. One less issue. Thanks.
