### ISSUE TITLE
What model.getUserFromClient should return?

### ISSUE THREAD

**Issue by esnunes** [oauthjs/node-oauth2-server#83]
It is not clear what getUserFromClient should return. Considering that this method is called during client_credentials grant type there shouldn't exist a user right? just the client.

Is it meant to return a pseudo-user which represents the client? In this case the authorise middleware should add this user to req.user right?

**Comment by igorescobar** [comment]
@thomseddon In my case we are just going to use `client_credentials` and we don't need to tight a client_id, client_secret to  `users table`. I couldn't see just by reading the RFC why the coupling exists. 

There is anyway to implement `model.getUserFromClient` method and still keep it generic in case that specific client is coupled to an user... there is some logic behind it that we could rely on it to implement it?
