### ISSUE TITLE
application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by teuteuguy** [oauthjs/node-oauth2-server#92]
Is there an actual reason for application/x-www-form-urlencoded being the only supported method for posting to get tokens ?

Why can't we use Json ?

**Comment by jmdacruz** [comment]
Just for the record, the OAuth2 spec specifies that the token endpoint MUST receive the request in the body using form encoding, that is, with content type `application/x-www-form-urlencoded`. Using JSON in this scenario is just plain wrong and would break compatibility with other OAuth2 clients.

The following is an example from RFC6749:

```
POST /token HTTP/1.1
Host: server.example.com
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
&redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb
```

You should only do this if you are 100% aware that you are breaking compatibility with standard OAuth2 clients, and you are fine with that.
